#!/bin/bash

# A script that waits for a "quit" message to be written to a FIFO and then exits.
# This is used to keep the X session open if Qtile crashes.

FIFO_BASE=/tmp/quitwait

FIFO=$FIFO_BASE`echo $DISPLAY | tr ':' '_'`

trap "echo \"Closing pipe '$FIFO'.\"; rm -f $FIFO" EXIT

echo "Opening pipe '$FIFO'."

if [[ ! -p $FIFO ]]; then
	mkfifo $FIFO
fi

while true; do
	if read line < $FIFO; then
		case $line in
			"quit")
				echo "Got quit message. Exiting."
				break
				;;

			*)
				echo "Got unknown message $line."
				;;
		esac
	fi
done

